#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

home:
    path: /
    controller: App\Controller\HomeController::index

admin:
    path: /admin
    controller: App\Controller\HomeController::admin

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

use_registration:
    path: /register
    controller: App\Controller\RegistrationController::registerAction