#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }


admin:
    path: /admin
    controller: App\Admin\Controller\AdminController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

user_registration:
    path: /register
    controller: App\Controller\RegistrationController::registerAction

content_path:
    path: /{slug}
    controller: App\Controller\ContentController::index

home:
    path: /
    controller: App\Controller\HomeController::index